name: Docker Image CI
# commentaires ....
on:
  push:
    branches: [ master ]
jobs: 
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:  
      IMAGE_NAME: graph-covid
      PROJECT_ID: myapp-219715
      RUN_REGION: europe-north1
      SERVICE_NAME: srvcovidgraph
      GIT_TAG: v0.1.0

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@v0
      with :
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credential: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)   
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
   
    - name: Deploy Image to cloud Run
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG" \
          --platform "managed" \
          --allow-unauthenticated







     

